openapi: 3.0.1
info:
  title: NothingRpcApi
  version: v1.0
paths:
  /NothingRpcApi:
    get:
      tags:
        - NothingRpcService
      summary: Получить список моделей
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NothingModelDto'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    post:
      tags:
        - NothingRpcService
      summary: Создать новую модель
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNothingModelDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NothingModelDto'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    put:
      tags:
        - NothingRpcService
      summary: Обновить существующую модель
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNothingModelDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NothingModelDto'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  '/NothingRpcApi/{Id}':
    get:
      tags:
        - NothingRpcService
      summary: Получить модель с указанным идентификатором
      parameters:
        - name: Id
          in: path
          description: Идентификатор модели
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NothingModelDto'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    delete:
      tags:
        - NothingRpcService
      summary: Удалить модель с указанным идентификатором
      parameters:
        - name: Id
          in: path
          description: Идентификатор модели
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NothingModelDto'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    Any:
      required:
        - '@type'
      type: object
      properties:
        '@type':
          type: string
      additionalProperties:
        $ref: '#/components/schemas/Value'
    CreateNothingModelDto:
      type: object
      properties:
        Name:
          type: string
          description: Имя модели
      additionalProperties: false
      description: Данные для создания модели
    KindOneofCase:
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      type: integer
      format: int32
    ListValue:
      type: object
      properties:
        values:
          type: array
          items:
            $ref: '#/components/schemas/Value'
          nullable: true
          readOnly: true
      additionalProperties: false
    NothingModelDto:
      type: object
      properties:
        Id:
          type: integer
          description: Идентификатор модели
          format: int32
        Name:
          type: string
          description: Имя модели
      additionalProperties: false
      description: Данные модели
    NullValue:
      enum:
        - 0
      type: integer
      format: int32
    Status:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/Any'
      additionalProperties: false
    Struct:
      type: object
      properties:
        fields:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Value'
          nullable: true
          readOnly: true
      additionalProperties: false
    UpdateNothingModelDto:
      type: object
      properties:
        Id:
          type: integer
          description: Идентификатор модели
          format: int32
        Name:
          type: string
          description: Имя модели
      additionalProperties: false
      description: Данные для обновления модели
    Value:
      type: object
      properties:
        nullValue:
          $ref: '#/components/schemas/NullValue'
        hasNullValue:
          type: boolean
          readOnly: true
        numberValue:
          type: number
          format: double
        hasNumberValue:
          type: boolean
          readOnly: true
        stringValue:
          type: string
          nullable: true
        hasStringValue:
          type: boolean
          readOnly: true
        boolValue:
          type: boolean
        hasBoolValue:
          type: boolean
          readOnly: true
        structValue:
          $ref: '#/components/schemas/Struct'
        listValue:
          $ref: '#/components/schemas/ListValue'
        kindCase:
          $ref: '#/components/schemas/KindOneofCase'
      additionalProperties: false
tags:
  - name: NothingRpcService
    description: Сервис бизнес логики