name: test_nothing_web_api
services:
  test_postgres_nothing_web_api_db:
    image: postgres
    container_name: test_postgres_nothing_web_api_db
    environment:
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "nothing_web_api_db"
      POSTGRES_USER: "nothing_web_api"
      POSTGRES_PASSWORD: "nothing_web_api"
    networks:
      - default
    ports:
      - "5359:5432"
    restart: unless-stopped
    volumes:
      - test_postgres_nothing_web_api_db:/var/lib/test_postgres_nothing_web_api_db
  test_nothing_web_api:
    image: test_nothing_web_api
    container_name: test_nothing_web_api
    build:
      args:
        CERTIFICATE_PASSWORD: "localhost"
        CONFIGURATION: "Release"
      context: ../
      dockerfile: NothingWebApi/Dockerfile
    depends_on:
      - test_postgres_nothing_web_api_db
    environment:
      ASPNETCORE_HTTP_PORTS: "8159"
      ASPNETCORE_HTTPS_PORTS: "8259"
      PATH_BASE: "/nothing-web-api"
      POSTGRES_HOST: "test_postgres_nothing_web_api_db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "nothing_web_api_db"
      POSTGRES_USER: "nothing_web_api"
      POSTGRES_PASSWORD: "nothing_web_api"
    links:
      - test_postgres_nothing_web_api_db
    networks:
      - default
    ports:
      - "8159:8159"
      - "8259:8259"
    restart: unless-stopped
networks:
  default:
    driver: bridge
volumes:
  test_postgres_nothing_web_api_db: