name: console_nothing_web_api_test
services:
  console_nothing_web_api_test_postgres_nothing_web_api_db:
    image: postgres
    container_name: console_nothing_web_api_test_postgres_nothing_web_api_db
    environment:
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "nothing_web_api_db"
      POSTGRES_USER: "nothing_web_api"
      POSTGRES_PASSWORD: "nothing_web_api"
    networks:
      - default
    ports:
      - "5759:5432"
    restart: unless-stopped
    volumes:
      - console_nothing_web_api_test_postgres_nothing_web_api_db:/var/lib/console_nothing_web_api_test_postgres_nothing_web_api_db
  console_nothing_web_api_test_nothing_web_api:
    image: console_nothing_web_api_test_nothing_web_api
    container_name: console_nothing_web_api_test_nothing_web_api
    build:
      args:
        CERTIFICATE_PASSWORD: "localhost"
        CONFIGURATION: "Release"
      context: ../
      dockerfile: NothingWebApi/Dockerfile
    depends_on:
      - console_nothing_web_api_test_postgres_nothing_web_api_db
    environment:
      ASPNETCORE_HTTP_PORTS: "8959"
      ASPNETCORE_HTTPS_PORTS: "9059"
      PATH_BASE: "/nothing-web-api"
      POSTGRES_HOST: "console_nothing_web_api_test_postgres_nothing_web_api_db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "nothing_web_api_db"
      POSTGRES_USER: "nothing_web_api"
      POSTGRES_PASSWORD: "nothing_web_api"
    links:
      - console_nothing_web_api_test_postgres_nothing_web_api_db
    networks:
      - default
    ports:
      - "8959:8959"
      - "9059:9059"
    restart: unless-stopped
networks:
  default:
    driver: bridge
volumes:
  console_nothing_web_api_test_postgres_nothing_web_api_db: